#!/bin/sh
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys
export PATH="/bin:/sbin:/usr/bin:/usr/sbin" PS1='# '
if [ -x /usr/bin/find-my-device-start ]; then
	/usr/bin/find-my-device-start &
fi
exec setsid cttyhack /bin/sh -i
